name: Build and Test Server

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches-ignore: [ "main" ]

defaults:
    run:
      working-directory: server

jobs:
  build_test:
    env:
      CI: true
      MONGO_TEST_URI: mongodb://localhost/TaskMaster

    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            node-version: [19.x]
            mongodb-version: ['4.4']
            
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Run Build and Test
      env:
        MONGO_TEST_URI: ${{ env.MONGO_TEST_URI }}
        CI: ${{ env.CI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        npm ci
        npm test